"""initial schema

Revision ID: a24a50b792ac
Revises:
Create Date: 2026-09-21 19:54:30.180301
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a24a50b792ac"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergens",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allergens")),
        sa.UniqueConstraint("code", name=op.f("uq_allergens_code")),
        sa.UniqueConstraint("name", name=op.f("uq_allergens_name")),
    )
    op.create_table(
        "ingredients",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
        sa.UniqueConstraint("name", name=op.f("uq_ingredients_name")),
    )
    op.create_table(
        "meals",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("price_nok", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein_grams", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("carbohydrate_grams", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("fat_grams", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("available", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("calories >= 0", name=op.f("ck_meals_calories_non_negative")),
        sa.CheckConstraint(
            "carbohydrate_grams >= 0", name=op.f("ck_meals_carbohydrate_non_negative")
        ),
        sa.CheckConstraint("fat_grams >= 0", name=op.f("ck_meals_fat_non_negative")),
        sa.CheckConstraint("price_nok >= 0", name=op.f("ck_meals_price_non_negative")),
        sa.CheckConstraint("protein_grams >= 0", name=op.f("ck_meals_protein_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meals")),
        sa.UniqueConstraint("name", name=op.f("uq_meals_name")),
    )
    op.create_table(
        "pickup_locations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address_line", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), server_default="Oslo", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pickup_locations")),
        sa.UniqueConstraint("name", name=op.f("uq_pickup_locations_name")),
    )
    op.create_table(
        "users",
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "role",
            sa.Enum("customer", "admin", name="user_role"),
            server_default="customer",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_external_subject"), "users", ["external_subject"], unique=True)
    op.create_table(
        "cart_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity <= 99", name=op.f("ck_cart_items_quantity_reasonable")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["meal_id"], ["meals.id"], name=op.f("fk_cart_items_meal_id_meals"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cart_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("user_id", "meal_id", name=op.f("uq_cart_items_user_id")),
    )
    op.create_index(op.f("ix_cart_items_user_id"), "cart_items", ["user_id"], unique=False)
    op.create_table(
        "meal_allergens",
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("allergen_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allergen_id"],
            ["allergens.id"],
            name=op.f("fk_meal_allergens_allergen_id_allergens"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            name=op.f("fk_meal_allergens_meal_id_meals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meal_id", "allergen_id", name=op.f("pk_meal_allergens")),
    )
    op.create_table(
        "meal_ingredients",
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_meal_ingredients_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_meal_ingredients_ingredient_id_ingredients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            name=op.f("fk_meal_ingredients_meal_id_meals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meal_id", "ingredient_id", name=op.f("pk_meal_ingredients")),
        sa.UniqueConstraint("meal_id", "position", name=op.f("uq_meal_ingredients_meal_id")),
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_location_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("received", "preparing", "ready_for_pickup", "completed", name="order_status"),
            server_default="received",
            nullable=False,
        ),
        sa.Column("pickup_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_location_name", sa.String(length=200), nullable=False),
        sa.Column("pickup_location_address", sa.String(length=400), nullable=False),
        sa.Column("total_nok", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pickup_end_at > pickup_start_at", name=op.f("ck_orders_pickup_window_valid")
        ),
        sa.CheckConstraint("total_nok >= 0", name=op.f("ck_orders_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["pickup_location_id"],
            ["pickup_locations.id"],
            name=op.f("fk_orders_pickup_location_id_pickup_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index("ix_orders_user_created_at", "orders", ["user_id", "created_at"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("meal_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("unit_price_nok", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_nok >= 0", name=op.f("ck_order_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            name=op.f("fk_order_items_meal_id_meals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "meal_id", name=op.f("uq_order_items_order_id")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_orders_user_created_at", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("meal_ingredients")
    op.drop_table("meal_allergens")
    op.drop_index(op.f("ix_cart_items_user_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_users_external_subject"), table_name="users")
    op.drop_table("users")
    op.drop_table("pickup_locations")
    op.drop_table("meals")
    op.drop_table("ingredients")
    op.drop_table("allergens")
    postgresql.ENUM(name="order_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="user_role").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
